### ISSUE TITLE
Change to appropriate cursor when hovering over course cards

### ISSUE THREAD

**Issue by TaiyyabAhmed97** [uiuc-mcs/uiuc-mcs#1]
The current cursor over the course cards is the default one and when over the title or subtitle, it is the text one. The UI would feel more cohesive if it was the pointer cursor as that is more natural over cards.

**Comment by djoldman** [comment]
Thanks, fixed in https://github.com/uiuc-mcs/uiuc-mcs/pull/2/commits/cd08eca0a01bc4df86b3b18fc1af534848537624
